#!/bin/bash

# ==========================================
# SESSIONS MODULE - sessions.sh
# ==========================================
# Persistent agentic session storage (P1.sessions-1).
#
# Storage layout:
#   ${CODER_SESSIONS_DIR:-${CONFIG_DIR:-$HOME/.config/coder-cli}/sessions}/<id>/
#     ├── messages.json   (raw messages array, provider-shaped, written verbatim
#     │                    by callers — typically the global CODER_AGENTIC_MESSAGES)
#     └── meta.json       ({id, provider, model, label, created_at, updated_at,
#                            turn_count})
#
# Session IDs: validated against `^[A-Za-z0-9_-]+$`. Auto-generated by
# `sessions_new` as `<YYYYMMDDHHMMSS>-<8hex>` (UTC + 4 random bytes).
#
# This module is pure: it does NOT integrate with the agentic loop or
# coder.sh — that is P1.sessions-2/3. The expected call pattern is:
#   id=$(sessions_new "anthropic" "claude-sonnet-4-6")
#   ... run agentic turn, CODER_AGENTIC_MESSAGES gets updated ...
#   sessions_save "$id" "$CODER_AGENTIC_MESSAGES"
#   ... later ...
#   msgs=$(sessions_load "$id")
#
# This file is sourced into the parent shell; do NOT enable `set -euo pipefail`
# globally here (would leak flags into coder.sh and legacy modules).
#
# Public contract (return codes: 0 ok, 1 state error, 2 input/usage error):
#   sessions_dir                                   echoes base sessions dir
#   sessions_init                                  mkdir base (idempotent)
#   sessions_new [provider] [model] [label]        echoes new id
#   sessions_exists <id>
#   sessions_save <id> <messages_json> [prov] [mdl]
#   sessions_load <id>                             emits messages.json content
#   sessions_meta <id>                             emits meta.json content
#   sessions_list                                  TSV: id\tturn_count\tupdated_at\tprovider\tlabel
#   sessions_remove <id>                           rm -rf the session dir (safe)

if [ -n "${_SESSIONS_LOADED:-}" ]; then
    return 0
fi
_SESSIONS_LOADED=1

# i18n fallback: hf_t existe aunque i18n.sh no esté cargado (tests sourcean directo).
type hf_t >/dev/null 2>&1 || hf_t() { if [ "${HF_LANG:-en}" = "es" ] && [ -n "${2:-}" ]; then printf '%s' "$2"; else printf '%s' "$1"; fi; }

# ---- helpers --------------------------------------------------------------

sessions_dir() {
    echo "${CODER_SESSIONS_DIR:-${CONFIG_DIR:-$HOME/.config/coder-cli}/sessions}"
}

# _sessions_valid_id <id> -> 0 ok, 2 invalid
# Locale-independent: a valid id is a non-empty ASCII string composed only of
# bytes in [A-Za-z0-9_-]. Path-traversal forms (slash, dot-dot, leading dot)
# are rejected up front (defense in depth — the byte filter also catches them
# but the explicit cases make intent obvious).
_sessions_valid_id() {
    local id="${1:-}"
    [ -n "$id" ] || return 2
    case "$id" in
        */*|*..*|.*) return 2 ;;
    esac
    local stripped
    stripped=$(printf '%s' "$id" | LC_ALL=C tr -d 'A-Za-z0-9_-')
    [ -z "$stripped" ] || return 2
    return 0
}

# _sessions_path <id> -> echoes "$base/$id". Does NOT validate id.
_sessions_path() {
    printf '%s/%s' "$(sessions_dir)" "$1"
}

# _sessions_now_iso -> echoes ISO-8601 UTC (e.g. 2026-05-16T12:34:56Z).
_sessions_now_iso() {
    date -u +%Y-%m-%dT%H:%M:%SZ
}

# _sessions_gen_id -> echoes a fresh id of the form <YYYYMMDDHHMMSS>-<8hex>.
_sessions_gen_id() {
    local ts hex
    ts=$(date -u +%Y%m%d%H%M%S)
    if [ -r /dev/urandom ]; then
        hex=$(od -An -N4 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n')
    fi
    if [ -z "${hex:-}" ]; then
        hex=$(printf '%08x' "$RANDOM$RANDOM" | tail -c 8)
    fi
    printf '%s-%s' "$ts" "$hex"
}

# _sessions_atomic_write <target_path> <content>
# Writes via mktemp + mv (intra-fs rename). Returns 1 on failure.
_sessions_atomic_write() {
    local target="$1" content="$2"
    local dir tmp
    dir=$(dirname "$target")
    [ -d "$dir" ] || return 1
    tmp=$(mktemp "${target}.XXXXXX" 2>/dev/null) || return 1
    printf '%s' "$content" >"$tmp" || { rm -f "$tmp"; return 1; }
    mv "$tmp" "$target" 2>/dev/null || { rm -f "$tmp"; return 1; }
    return 0
}

# ---- public API -----------------------------------------------------------

sessions_init() {
    local base
    base=$(sessions_dir)
    mkdir -p "$base" 2>/dev/null || return 1
    return 0
}

# sessions_new [provider] [model] [label]
# Creates a fresh session directory with an empty messages array and initial
# meta. Echoes the new id to stdout. rc 0 ok, 1 state error.
sessions_new() {
    local provider="${1:-}" model="${2:-}" label="${3:-}"
    local base id path meta now
    base=$(sessions_dir)
    mkdir -p "$base" 2>/dev/null || return 1

    # Retry up to 5 times if collision (extremely unlikely with 4 random bytes
    # + per-second timestamp, but cheap to guard).
    local attempt=0
    while [ "$attempt" -lt 5 ]; do
        id=$(_sessions_gen_id)
        path="$base/$id"
        if mkdir "$path" 2>/dev/null; then
            break
        fi
        id=""
        attempt=$((attempt + 1))
    done
    [ -n "$id" ] || return 1

    now=$(_sessions_now_iso)
    meta=$(jq -n \
        --arg id "$id" \
        --arg provider "$provider" \
        --arg model "$model" \
        --arg label "$label" \
        --arg now "$now" \
        '{id: $id, provider: $provider, model: $model, label: $label,
          created_at: $now, updated_at: $now, turn_count: 0}') || return 1

    _sessions_atomic_write "$path/meta.json" "$meta" || return 1
    _sessions_atomic_write "$path/messages.json" "[]" || return 1
    echo "$id"
    return 0
}

# sessions_exists <id> -> 0 yes, 1 no, 2 invalid id
sessions_exists() {
    local id="${1:-}"
    _sessions_valid_id "$id" || return 2
    [ -d "$(_sessions_path "$id")" ] || return 1
    return 0
}

# sessions_save <id> <messages_json> [provider] [model]
# Overwrites messages.json (validated as JSON), bumps updated_at + turn_count
# in meta.json. provider/model are optional overrides — empty preserves
# existing values. rc 0 ok, 1 state error, 2 invalid id/json.
sessions_save() {
    local id="${1:-}" messages_json="${2-}" provider="${3:-}" model="${4:-}"
    _sessions_valid_id "$id" || { echo "sessions_save: invalid id: $id" >&2; return 2; }
    [ -n "$messages_json" ] || { echo "sessions_save: empty messages_json" >&2; return 2; }

    local path
    path=$(_sessions_path "$id")
    [ -d "$path" ] || { echo "sessions_save: session not found: $id" >&2; return 1; }

    # Validate messages_json is valid JSON.
    if ! printf '%s' "$messages_json" | jq empty >/dev/null 2>&1; then
        echo "sessions_save: messages_json is not valid JSON" >&2
        return 2
    fi

    _sessions_atomic_write "$path/messages.json" "$messages_json" || return 1

    local now meta_in meta_out
    now=$(_sessions_now_iso)
    if [ -f "$path/meta.json" ]; then
        meta_in=$(cat "$path/meta.json" 2>/dev/null)
    fi
    if [ -z "${meta_in:-}" ] || ! printf '%s' "$meta_in" | jq empty >/dev/null 2>&1; then
        # Corrupted or missing — rebuild minimal meta.
        meta_in=$(jq -n --arg id "$id" --arg now "$now" \
            '{id: $id, provider: "", model: "", label: "",
              created_at: $now, updated_at: $now, turn_count: 0}')
    fi

    meta_out=$(printf '%s' "$meta_in" | jq \
        --arg now "$now" \
        --arg provider "$provider" \
        --arg model "$model" \
        '
        .updated_at = $now
        | .turn_count = ((.turn_count // 0) + 1)
        | if ($provider | length) > 0 then .provider = $provider else . end
        | if ($model | length) > 0 then .model = $model else . end
        ') || return 1

    _sessions_atomic_write "$path/meta.json" "$meta_out" || return 1
    return 0
}

# sessions_load <id> -> emits messages.json content. rc 0/1/2.
sessions_load() {
    local id="${1:-}"
    _sessions_valid_id "$id" || { echo "sessions_load: invalid id: $id" >&2; return 2; }
    local path
    path=$(_sessions_path "$id")
    [ -d "$path" ] || { echo "sessions_load: session not found: $id" >&2; return 1; }
    [ -f "$path/messages.json" ] || { echo "sessions_load: messages.json missing for $id" >&2; return 1; }
    cat "$path/messages.json"
    return 0
}

# sessions_meta <id> -> emits meta.json content. rc 0/1/2.
sessions_meta() {
    local id="${1:-}"
    _sessions_valid_id "$id" || { echo "sessions_meta: invalid id: $id" >&2; return 2; }
    local path
    path=$(_sessions_path "$id")
    [ -d "$path" ] || { echo "sessions_meta: session not found: $id" >&2; return 1; }
    [ -f "$path/meta.json" ] || { echo "sessions_meta: meta.json missing for $id" >&2; return 1; }
    cat "$path/meta.json"
    return 0
}

# sessions_list -> TSV (one per session): id\tturn_count\tupdated_at\tprovider\tlabel
# Sorted by updated_at desc (ISO-8601 sorts lexicographically).
# rc 0 always; emits empty if no sessions exist.
sessions_list() {
    local base
    base=$(sessions_dir)
    [ -d "$base" ] || return 0

    local entry id meta tc updated provider label
    for entry in "$base"/*/; do
        [ -d "$entry" ] || continue
        id=$(basename "$entry")
        _sessions_valid_id "$id" || continue
        [ -f "$entry/meta.json" ] || continue
        meta=$(cat "$entry/meta.json" 2>/dev/null)
        [ -n "$meta" ] || continue
        if ! printf '%s' "$meta" | jq empty >/dev/null 2>&1; then
            continue
        fi
        tc=$(printf '%s' "$meta" | jq -r '.turn_count // 0')
        updated=$(printf '%s' "$meta" | jq -r '.updated_at // ""')
        provider=$(printf '%s' "$meta" | jq -r '.provider // ""')
        label=$(printf '%s' "$meta" | jq -r '.label // ""')
        # Sanitize TSV-breaking chars in label/provider (defensive).
        label=$(printf '%s' "$label" | tr '\t\n' '  ')
        provider=$(printf '%s' "$provider" | tr '\t\n' '  ')
        printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$tc" "$updated" "$provider" "$label"
    done | sort -t"$(printf '\t')" -k3,3 -r
    return 0
}

# sessions_remove <id> -> rm -rf the session dir.
# Safety: validates id format, verifies target is a direct child of
# sessions_dir, verifies it looks like a session (contains meta.json OR
# messages.json), refuses anything else.
# rc 0 ok, 1 state error, 2 invalid id.
sessions_remove() {
    local id="${1:-}"
    _sessions_valid_id "$id" || { echo "sessions_remove: invalid id: $id" >&2; return 2; }

    local base path
    base=$(sessions_dir)
    path="$base/$id"

    [ -d "$path" ] || { echo "sessions_remove: session not found: $id" >&2; return 1; }

    # Resolve absolute paths (no symlink follow surprises) and re-check
    # that target is a direct child of base.
    local base_abs path_abs path_parent_abs
    base_abs=$(cd "$base" 2>/dev/null && pwd -P) || {
        echo "sessions_remove: cannot resolve base dir" >&2; return 1; }
    path_abs=$(cd "$path" 2>/dev/null && pwd -P) || {
        echo "sessions_remove: cannot resolve session path" >&2; return 1; }
    path_parent_abs=$(dirname "$path_abs")
    if [ "$path_parent_abs" != "$base_abs" ]; then
        echo "sessions_remove: refusing to remove path outside sessions dir: $path_abs" >&2
        return 1
    fi

    # Sanity: must look like a session dir.
    if [ ! -f "$path/meta.json" ] && [ ! -f "$path/messages.json" ]; then
        echo "sessions_remove: $id does not look like a session (no meta.json/messages.json)" >&2
        return 1
    fi

    rm -rf "$path" || return 1
    return 0
}

# ---- legacy historial_*.txt migration (P1.sessions-4) ---------------------
#
# The pre-sessions chat mode in lib/llm_communication.sh persists conversation
# state as `$CONFIG_DIR/historial_<YYYYMMDD>_<HHMMSS>.txt` — a single text blob
# of the accumulated prompt. There is no structured user/assistant split there.
#
# Migration policy (best-effort):
#   * Each historial file becomes one session whose messages.json is a JSON
#     array with a single `{"role":"user","content":"<raw file content>"}` entry.
#     The user can resume + chat onward; previous turns appear as context.
#   * meta.json carries `origin:"legacy_historial"`, `legacy_path:<abs path>`,
#     `legacy_basename:historial_*.txt`, and `created_at`/`updated_at` parsed
#     from the filename when possible (falls back to "now" on parse miss).
#   * Idempotent: if a session already exists with `meta.legacy_path == file`,
#     it is skipped on re-run.
#   * Empty files are skipped (avoid noise sessions).
#   * Default keeps the legacy .txt in place; pass --remove-legacy to delete
#     after a successful migration.

# _sessions_find_by_legacy_path <abs_path>
# Echoes the id of the existing session whose meta.legacy_path matches, or
# nothing if none. rc 0 found, 1 not found.
_sessions_find_by_legacy_path() {
    local target="${1:-}"
    [ -n "$target" ] || return 1
    local base
    base=$(sessions_dir)
    [ -d "$base" ] || return 1
    local entry id meta lp
    for entry in "$base"/*/; do
        [ -d "$entry" ] || continue
        id=$(basename "$entry")
        _sessions_valid_id "$id" || continue
        [ -f "$entry/meta.json" ] || continue
        meta=$(cat "$entry/meta.json" 2>/dev/null) || continue
        [ -n "$meta" ] || continue
        printf '%s' "$meta" | jq empty >/dev/null 2>&1 || continue
        lp=$(printf '%s' "$meta" | jq -r '.legacy_path // ""')
        if [ "$lp" = "$target" ]; then
            echo "$id"
            return 0
        fi
    done
    return 1
}

# sessions_migrate_legacy [--dry-run] [--remove-legacy] [--from <dir>]
# Scans <dir> (default $CONFIG_DIR or $HOME/.config/coder-cli) for files matching
# `historial_*.txt` and migrates each to a session. Emits one line per file
# (MIGRATE / SKIP / DRY-RUN / ERROR) and a `summary:` line at the end.
# rc 0 ok (even if 0 files), 1 state error, 2 usage error.
sessions_migrate_legacy() {
    local from_dir="${CONFIG_DIR:-$HOME/.config/coder-cli}"
    local dry_run=0
    local remove_legacy=0

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --dry-run) dry_run=1; shift ;;
            --remove-legacy) remove_legacy=1; shift ;;
            --from)
                shift
                if [ "$#" -lt 1 ]; then
                    echo "sessions_migrate_legacy: --from needs <dir>" >&2
                    return 2
                fi
                from_dir="$1"
                shift
                ;;
            --from=*)
                from_dir="${1#--from=}"
                shift
                ;;
            *)
                echo "sessions_migrate_legacy: unknown flag: $1" >&2
                return 2
                ;;
        esac
    done

    if [ ! -d "$from_dir" ]; then
        echo "sessions_migrate_legacy: directory not found: $from_dir" >&2
        return 1
    fi
    sessions_init || return 1

    local migrated=0 skipped=0 total=0
    local file basename ts iso label content content_size existing
    local messages meta base id path attempt

    for file in "$from_dir"/historial_*.txt; do
        # Without nullglob, an unmatched glob expands to itself — `-f` guards it.
        [ -f "$file" ] || continue
        total=$((total + 1))
        basename=$(basename "$file")

        existing=""
        existing=$(_sessions_find_by_legacy_path "$file" 2>/dev/null) || true
        if [ -n "$existing" ]; then
            echo "SKIP $basename (already migrated as $existing)"
            skipped=$((skipped + 1))
            continue
        fi

        content_size=$(wc -c <"$file" 2>/dev/null | tr -d ' ')
        if [ "${content_size:-0}" -eq 0 ]; then
            echo "SKIP $basename (empty)"
            skipped=$((skipped + 1))
            continue
        fi

        # Parse `historial_YYYYMMDD_HHMMSS.txt`. The legacy writer uses local
        # time; we record it as-is without TZ conversion (tagged with Z purely
        # as ISO-8601 format compliance — origin field flags it as legacy).
        ts="${basename#historial_}"
        ts="${ts%.txt}"
        if [[ "$ts" =~ ^([0-9]{4})([0-9]{2})([0-9]{2})_([0-9]{2})([0-9]{2})([0-9]{2})$ ]]; then
            iso="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}-${BASH_REMATCH[3]}T${BASH_REMATCH[4]}:${BASH_REMATCH[5]}:${BASH_REMATCH[6]}Z"
            label="Legacy ${BASH_REMATCH[1]}-${BASH_REMATCH[2]}-${BASH_REMATCH[3]}"
        else
            iso=$(_sessions_now_iso)
            label="Legacy $basename"
        fi

        if [ "$dry_run" -eq 1 ]; then
            echo "DRY-RUN $basename -> (would create session, label='$label', created_at=$iso)"
            migrated=$((migrated + 1))
            continue
        fi

        # Preserve trailing newlines (legacy `echo > file` always appends one):
        # `$(cat)` strips them, so append a sentinel and trim it post-capture.
        content=$(cat "$file"; printf .) || {
            echo "ERROR $basename (failed to read)"
            skipped=$((skipped + 1))
            continue
        }
        content="${content%.}"
        messages=$(jq -n --arg c "$content" '[{role:"user",content:$c}]') || {
            echo "ERROR $basename (jq build messages failed)"
            skipped=$((skipped + 1))
            continue
        }

        # Allocate session dir directly (sessions_new would set created_at=now
        # and we need it set from the historial filename when parseable).
        base=$(sessions_dir)
        id=""
        attempt=0
        while [ "$attempt" -lt 5 ]; do
            id=$(_sessions_gen_id)
            path="$base/$id"
            if mkdir "$path" 2>/dev/null; then
                break
            fi
            id=""
            attempt=$((attempt + 1))
        done
        if [ -z "$id" ]; then
            echo "ERROR $basename (could not allocate session dir)"
            skipped=$((skipped + 1))
            continue
        fi

        meta=$(jq -n \
            --arg id "$id" \
            --arg label "$label" \
            --arg created "$iso" \
            --arg legacy_path "$file" \
            --arg legacy_basename "$basename" \
            '{id:$id, provider:"", model:"", label:$label,
              created_at:$created, updated_at:$created, turn_count:0,
              origin:"legacy_historial",
              legacy_path:$legacy_path,
              legacy_basename:$legacy_basename}') || {
            echo "ERROR $basename (jq build meta failed)"
            rm -rf "$path"
            skipped=$((skipped + 1))
            continue
        }

        if ! _sessions_atomic_write "$path/meta.json" "$meta"; then
            echo "ERROR $basename (failed writing meta.json)"
            rm -rf "$path"
            skipped=$((skipped + 1))
            continue
        fi
        if ! _sessions_atomic_write "$path/messages.json" "$messages"; then
            echo "ERROR $basename (failed writing messages.json)"
            rm -rf "$path"
            skipped=$((skipped + 1))
            continue
        fi

        echo "MIGRATE $basename -> $id"
        migrated=$((migrated + 1))

        if [ "$remove_legacy" -eq 1 ]; then
            rm -f "$file" 2>/dev/null || echo "WARN failed to remove $file" >&2
        fi
    done

    if [ "$total" -eq 0 ]; then
        echo "(no historial files found in $from_dir)"
    fi
    echo "summary: $migrated migrated, $skipped skipped, $total total"
    return 0
}

# ==========================================
# CLI dispatcher (`coder sessions ...`)
# ==========================================

_sessions_cli_usage() {
    printf '%s\n' "$(hf_t "Usage: coder sessions <subcommand> [args]" "Uso: coder sessions <subcommand> [args]")"
    cat <<'EOF'

Subcommands:
  list                                List saved sessions (id, turns, updated, provider, label).
  show <id>                           Print metadata (provider, model, turn/message counts, path).
  remove <id>                         Delete the session directory <id>.
  resume <id>                         Resume <id> in agentic interactive mode
                                      (alias for `coder --session <id>`).
  migrate [--dry-run] [--remove-legacy] [--from <dir>]
                                      Convert legacy historial_*.txt files in
                                      $CONFIG_DIR (or --from <dir>) into sessions.
                                      Idempotent (skips already-migrated files).

Examples:
  coder sessions list
  coder sessions show 20260516143012-ab12cd34
  coder sessions remove 20260516143012-ab12cd34
  coder sessions resume 20260516143012-ab12cd34
  coder sessions migrate --dry-run
  coder sessions migrate --remove-legacy
EOF
}

# sessions_cli <subcommand> [<args>...]
# Exit codes: 0 ok, 1 state error (not found, read/delete fail, missing
# dependency for resume), 2 usage error (missing/extra args, bad id format,
# unknown subcommand).
sessions_cli() {
    local sub="${1:-}"
    case "$sub" in
        list)
            shift
            if [ "$#" -ne 0 ]; then
                echo "sessions list: unexpected arguments" >&2
                _sessions_cli_usage >&2
                return 2
            fi
            local rows
            rows=$(sessions_list)
            if [ -z "$rows" ]; then
                echo "(no sessions)"
                return 0
            fi
            printf '%-32s %-6s %-22s %-12s %s\n' "ID" "TURNS" "UPDATED" "PROVIDER" "LABEL"
            local id tc updated provider label
            while IFS=$'\t' read -r id tc updated provider label; do
                [ -n "$id" ] || continue
                printf '%-32s %-6s %-22s %-12s %s\n' "$id" "$tc" "$updated" "$provider" "$label"
            done <<<"$rows"
            ;;
        show)
            shift
            if [ "$#" -ne 1 ]; then
                echo "sessions show: expected <id>" >&2
                _sessions_cli_usage >&2
                return 2
            fi
            local id="$1"
            sessions_exists "$id"
            local rc=$?
            if [ "$rc" -eq 2 ]; then
                echo "sessions show: invalid id: $id" >&2
                return 2
            elif [ "$rc" -ne 0 ]; then
                echo "sessions show: session not found: $id" >&2
                return 1
            fi
            local meta path msg_count
            if ! meta=$(sessions_meta "$id" 2>/dev/null); then
                echo "sessions show: cannot read meta.json for $id" >&2
                return 1
            fi
            path=$(_sessions_path "$id")
            msg_count="?"
            if [ -f "$path/messages.json" ]; then
                msg_count=$(jq 'length' <"$path/messages.json" 2>/dev/null)
                [ -n "$msg_count" ] || msg_count="?"
            fi
            local created_at updated_at provider model label turn_count
            created_at=$(printf '%s' "$meta" | jq -r '.created_at // ""')
            updated_at=$(printf '%s' "$meta" | jq -r '.updated_at // ""')
            provider=$(printf '%s' "$meta" | jq -r '.provider // ""')
            model=$(printf '%s' "$meta" | jq -r '.model // ""')
            label=$(printf '%s' "$meta" | jq -r '.label // ""')
            turn_count=$(printf '%s' "$meta" | jq -r '.turn_count // 0')
            printf 'id: %s\n' "$id"
            printf 'created_at: %s\n' "$created_at"
            printf 'updated_at: %s\n' "$updated_at"
            printf 'provider: %s\n' "$provider"
            printf 'model: %s\n' "$model"
            printf 'label: %s\n' "$label"
            printf 'turn_count: %s\n' "$turn_count"
            printf 'message_count: %s\n' "$msg_count"
            printf 'path: %s\n' "$path"
            ;;
        remove|rm)
            shift
            if [ "$#" -ne 1 ]; then
                echo "sessions remove: expected <id>" >&2
                _sessions_cli_usage >&2
                return 2
            fi
            local id="$1"
            sessions_exists "$id"
            local rc=$?
            if [ "$rc" -eq 2 ]; then
                echo "sessions remove: invalid id: $id" >&2
                return 2
            elif [ "$rc" -ne 0 ]; then
                echo "sessions remove: session not found: $id" >&2
                return 1
            fi
            if ! sessions_remove "$id"; then
                return 1
            fi
            echo "removed: $id"
            ;;
        resume)
            shift
            if [ "$#" -ne 1 ]; then
                echo "sessions resume: expected <id>" >&2
                _sessions_cli_usage >&2
                return 2
            fi
            local id="$1"
            sessions_exists "$id"
            local rc=$?
            if [ "$rc" -eq 2 ]; then
                echo "sessions resume: invalid id: $id" >&2
                return 2
            elif [ "$rc" -ne 0 ]; then
                echo "sessions resume: session not found: $id" >&2
                return 1
            fi
            if ! declare -f modo_agentico_interactivo >/dev/null; then
                echo "sessions resume: agentic mode not available (lib/tool_calling.sh missing)" >&2
                return 1
            fi
            if declare -f get_api_config >/dev/null; then
                get_api_config
            fi
            export CODER_RESUME_SESSION_ID="$id"
            modo_agentico_interactivo
            ;;
        migrate)
            shift
            local mig_from="" mig_dry=0 mig_remove=0
            while [ "$#" -gt 0 ]; do
                case "$1" in
                    --dry-run) mig_dry=1; shift ;;
                    --remove-legacy) mig_remove=1; shift ;;
                    --from)
                        shift
                        if [ "$#" -lt 1 ]; then
                            echo "sessions migrate: --from needs <dir>" >&2
                            _sessions_cli_usage >&2
                            return 2
                        fi
                        mig_from="$1"
                        shift
                        ;;
                    --from=*)
                        mig_from="${1#--from=}"
                        shift
                        ;;
                    -h|--help)
                        _sessions_cli_usage
                        return 0
                        ;;
                    *)
                        echo "sessions migrate: unknown argument: $1" >&2
                        _sessions_cli_usage >&2
                        return 2
                        ;;
                esac
            done
            local mig_args=()
            [ "$mig_dry" -eq 1 ] && mig_args+=(--dry-run)
            [ "$mig_remove" -eq 1 ] && mig_args+=(--remove-legacy)
            if [ -n "$mig_from" ]; then
                mig_args+=(--from "$mig_from")
            fi
            # Bash 3.2 portability: empty-array expansion under `set -u` is
            # only safe via the `${arr[@]+...}` guard.
            sessions_migrate_legacy ${mig_args[@]+"${mig_args[@]}"}
            return $?
            ;;
        -h|--help|help)
            _sessions_cli_usage
            return 0
            ;;
        "")
            _sessions_cli_usage >&2
            return 2
            ;;
        *)
            echo "sessions: unknown subcommand '$sub'" >&2
            _sessions_cli_usage >&2
            return 2
            ;;
    esac
}
